

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import  ClientProvider  from '../components/ClientProvider'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
        <div className="mx-auto max-w-screen-lg h-screen flex flex-col">
          <Navbar/>
       <div className="flex-grow">
       
       {children}
       
       </div>
        </div>
        </ClientProvider>
      </body>
    </html>
  
  );
}
